### PR TITLE
add readme, .gz support, resolves #1

### LINKED ISSUE #1: add support for .gz files
In other words if you have a file like:

```
touch test.json
```

I often run something like
```
gzip --best test.json

# gunzip test.json.gz to reverse
```

to compress it

dont think there would be any complications with adding, will make a PR

### PR DESCRIPTION
**Pull request by seanbreckenridge**

### CODE REVIEW

**Comment by seanbreckenridge** [comment]
wasnt sure if I should do it without asking, but making this a library [seems like a good time to deprecate this](https://github.com/karlicoss/kompress/pull/3/files#diff-f4d7f47c0bb5dfd0db837452a77640fcecb987417005a4e448ddff568c924155R174)?

wrote up some docs as well since I know you're not a fan of doing that (btw, I don't really mind writing docs so if you ever want some help with that feel free to ping me)

**Comment by karlicoss** [comment]
thanks! and yeah really appreciate the readme!

**Comment by seanbreckenridge** [comment]
Personally I always tend to edge on the side of caution when naming things the same as builtins

Can't know what the downstream user is going to do, even if you document and say not to do a * import -- better to prevent them from shooting themselves in the foot

**Comment by seanbreckenridge** [comment]
Not saying to remove it or anything though, if its something you think might be nice to have, can just remove the note to deprecate it

**Comment by karlicoss** [comment]
Yeah good point to be cautious. I think best to remove `open` from `kompress` then -- and keep backwards compatibility + a proper deprecation warning in HPI

**Pull request merged**
